=== enriquecr1990/masterunirmex/materias/1er_semestre/letw/dtd_a_schema_xml/dtd/vehiculos.dtd
<!--
Document Type Definition DTD
1.  DTD para la Concesionaria de autos donde la rama principal es Concesionaria, donde Tendra como NMTOKEN
    el nombre de la compañia
2.  Tiene como elementos hijos ListaVehiculos (de cero a uno elementos) y PiePagina (solamente es un PCDATA)
3.  Para la rama ListaVehiculos donde tendra como NMTOKENS los tipos de vehiculos que ofrece la concesionaria,
    un elemento de Motos, Carros o Camionetas.
4.  Para la rama de Motos tendra por lo menos un elemento de Moto.
5.  Para la rama de Moto tendra el elemento Automovil y tiene como atributo el motoID el cual es unico
6.  Para la rama de Carros tendra por lo menos un elemento de Carro
7.  Para la rama de Carro tendra el elemento Automovil, el atrituto carroID y el elemento TipoCarro (elemento EMPTY)
    y esté ultimo tendra el atributo Diseno con posibles valores: Coupe|Hatchback|Sedan|Convertible
8.  Para la rama de Camionetas tendra por lo menos un elemento Camioneta
9.  Para la rama de Camioneta tendra el elemento Automovil, el atributo camionetaID y el elemento
    TipoCamioneta (elemento EMPTY) y esté ultimo tendra el atritubo Diseno con los posibles valores:
    Carga|Minivan|4x4|DobleCabina
10. Para el elemento de Automovil es donde tiene todos los elementos basicos como Marca, modelo, anio, version, color,
    kilometraje y la descripcion del automovil, tiene como atributos si su condicion es nuevo|seminuevo y cual es su
    transmisión, ademas de haber agregado las notaciones para el tratado de imagenes del automovil
 -->
<!ELEMENT Concesionaria (ListaVehiculos?, PiePagina?) >
    <!ATTLIST Concesionaria Compania NMTOKEN #REQUIRED>

    <!ELEMENT ListaVehiculos (Motos?,Carros?,Camionetas?)>
        <!ATTLIST ListaVehiculos TiposVehiculos NMTOKENS #REQUIRED >
        <!ELEMENT Motos (Moto+) >
            <!ELEMENT Moto (Automovil) >
            <!ATTLIST Moto motoID ID #REQUIRED >
        <!ELEMENT Carros (Carro+) >
            <!ELEMENT Carro (Automovil,TipoCarro) >
            <!ATTLIST Carro carroID ID #REQUIRED mejoraCarroID IDREF #IMPLIED >
            <!ELEMENT TipoCarro EMPTY >
            <!ATTLIST TipoCarro Diseno (Coupe|Hatchback|Sedan|Convertible) #REQUIRED>
        <!ELEMENT Camionetas (Camioneta) >
            <!ELEMENT Camioneta (Automovil,TipoCamioneta) >
            <!ATTLIST Camioneta camionetaID ID #REQUIRED>
            <!ELEMENT TipoCamioneta EMPTY >
            <!ATTLIST TipoCamioneta Diseno (Carga|Minivan|4x4|DobleCabina) #REQUIRED>

    <!ELEMENT Automovil (Marca, Modelo, Color, Precio, Kilometraje, Descripcion ) >
        <!ATTLIST Automovil Condicion (Nuevo | Seminuevo) #REQUIRED>
        <!ATTLIST Automovil Transmision (Manual | Automatico) #REQUIRED >
        <!ATTLIST Automovil Imagen CDATA #IMPLIED
                TipoImagen NOTATION (jpg | png) #IMPLIED >
        <!ELEMENT Marca (#PCDATA) >
        <!ELEMENT Modelo (#PCDATA|Anio|Version)* >
        <!ELEMENT Anio (#PCDATA) >
        <!ELEMENT Version (#PCDATA) >
        <!ELEMENT Color (#PCDATA) >
        <!ELEMENT Precio (#PCDATA) >
        <!ELEMENT Kilometraje (#PCDATA) >
        <!ELEMENT Descripcion (#PCDATA) >

        <!NOTATION jpg SYSTEM "image/jpeg" >
        <!NOTATION png SYSTEM "image/png" >

    <!ELEMENT PiePagina (#PCDATA) >

=== enriquecr1990/masterunirmex/materias/1er_semestre/letw/creacion_dtd/vehiculos_sin_xsl.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Concesionaria SYSTEM "dtd/vehiculos.dtd" [
		<!ENTITY Alumno "Enrique Corona Ricaño">
		<!ENTITY Materia "Lenguajes, Estándares y Tecnologías para la Web">
		]>
<Concesionaria Compania="EnriqueAsociados">
	<ListaVehiculos TiposVehiculos="Motos Carros Camionetas">
		<Motos>
			<Moto motoID="Moto1">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/yamaha-mt15.jpg" TipoImagen="jpg">
					<Marca>Yamaha</Marca>
					<Modelo>
						MT-15
						<Anio>2020</Anio>
					</Modelo>
					<Color>Rojo con Negro</Color>
					<Precio>85999.99</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Con un motor de alta tecnología, una carrocería compacta y un diseño propio de la linea MT de próxima generación, esta nueva y emocionante motocicleta no tiene comparación. Prepárate para activar tu lado oscuro. Porque esta ligera Hyper Naked va a transformar tu mundo. La nueva MT-15, gracias a su aspecto agresivo, demuestra toda su actitud incluso cuando no se mueve. Las nuevas y llamativas luces de posición dobles aportan a esta Hyper Naked ultraligera el aspecto más intimidante de su categoría. La robusta carrocería echada hacia adelante parece lista para atacar en cualquier momento. </Descripcion>
				</Automovil>
			</Moto>
		</Motos>
		<Carros>
			<Carro carroID="cSpark2021">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/chevrolet-spark-2020.png" TipoImagen="png">
					<Marca>Chevrolet</Marca>
					<Modelo>
						Spark
						<Anio>2021</Anio>
					</Modelo>
					<Color>Azul Metálico</Color>
					<Precio>183700.00</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Chevrolet Spark es el auto para ti, pues gracias a su tecnología y equipamiento te da info-entretenimiento, conectividad y seguridad únicos.</Descripcion>
				</Automovil>
				<TipoCarro Diseno="Hatchback" />
			</Carro>
			<Carro carroID="fFusion2019">
				<Automovil Condicion="Seminuevo" Transmision="Automatico" Imagen="imagenes/ford-fusion-2019-sedan.jpg" TipoImagen="jpg">
					<Marca>Ford</Marca>
					<Modelo>
						Fusion
						<Anio>2019</Anio>
					</Modelo>
					<Color>Azul Marino Metalizado</Color>
					<Precio>175999.00</Precio>
					<Kilometraje>30000</Kilometraje>
					<Descripcion>Déjate cautivar por Ford Fusion 2020, auto sedán de espectacular, el conjunto de tecnologías pensadas para brindarte una experiencia de conducción llena de confort, dinamismo y seguridad al máximo. ¡Descúbrelo! </Descripcion>
				</Automovil>
				<TipoCarro Diseno="Sedan" />
			</Carro>
			<Carro  carroID="fFusion2020" mejoraCarroID="fFusion2019">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/ford-fusion-2020-sedan.jpg" TipoImagen="jpg">
					<Marca>Ford</Marca>
					<Modelo>
						Fusion
						<Anio>2020</Anio>
					</Modelo>
					<Color>Blanco</Color>
					<Precio>265800.00</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Déjate cautivar por Ford Fusion 2020, auto sedán de espectacular Diseño equipado con Co-Pilot360, el conjunto de tecnologías pensadas para brindarte una experiencia de conducción llena de confort, dinamismo y seguridad al máximo. ¡Descúbrelo! </Descripcion>
				</Automovil>
				<TipoCarro Diseno="Sedan" />
			</Carro>
		</Carros>
		<Camionetas>
			<Camioneta camionetaID="camioneta0001">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/ford-ranger-2020.jpg" TipoImagen="jpg" >
					<Marca>Ford</Marca>
					<Modelo>
						Ranger
						<Anio>2020</Anio>
					</Modelo>
					<Color>Azul Metalizado</Color>
					<Precio>424600.00</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Ya sea que conduzcas por placer o trabajo, Ford Ranger 2020 tiene el Poder y Resistencia necesarios para acompañarte en cualquier actividad. ¡Ford Ranger 2020 tiene todo lo que deseas de una Camioneta Pick Up!</Descripcion>
				</Automovil>
				<TipoCamioneta Diseno="DobleCabina" />
			</Camioneta>
		</Camionetas>
	</ListaVehiculos>
	<PiePagina>
		Estudiante: &Alumno; - Materia: &Materia;
	</PiePagina>
</Concesionaria>

<!--
las entidades se cargaron en las cabeceras del doctype en donde carga el DTD para el xml
El DTD que se creo se hizo en base a una posible informacion que manejaria una Concesionaria de automoviles,
tanto de nuevos como usados; estan categorizados por motos, carros y camionetas.

Para una de las ramificaciones use una general que se usa para la moto, carro y camioneta la cual es Automovil
donde se encuentran todos los atributos comunes de cada automovil (marca, modelo, color, precio, kilometraje y descripcion)
ya por cada tipo tendra elementos adicionales que difieren entre cada vehiculo como el tipo de camioneta o el tipo de carro

-->
