=== enriquecr1990/masterunirmex/materias/1er_semestre/letw/dtd_a_schema_xml/xsd/vehiculos_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!--
        elemento raiz de la schema xml, en este caso se llama concesionaria
        tiene como atributo el nombre de la Compañia
        y como elementos ListaVehiculos y el PiePagina
    -->
    <xs:element name="Concesionaria">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="ListaVehiculos"/>
                <xs:element ref="PiePagina"/>
            </xs:sequence>
            <xs:attribute name="Compania" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- el elemento lista de vehiculos que es uno hijo del de Concesionaria,
         este elemento contiene como atributo el tipo de vehiculos y como elementos
         hijos: Motos, Carros y Camionetas -->
    <xs:element name="ListaVehiculos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Motos"/>
                <xs:element ref="Carros"/>
                <xs:element ref="Camionetas"/>
            </xs:sequence>
            <xs:attribute name="TiposVehiculos" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <!-- Elemento Motos que es uno hijo del de Lista Vehiculos
     Tiene como elemento Hijo la Moto-->
    <xs:element name="Motos">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Moto" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- Elemento moto que tiene como atributo motoID y como elemento hijo automovil -->
    <xs:element name="Moto">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Automovil"/>
            </xs:sequence>
            <xs:attribute name="motoID" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Elemento Carros que es uno hijo del de Lista Vehiculos
     Tiene como elemento Hijo la Carro-->
    <xs:element name="Carros">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Carro" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- elemento carro que tiene como atributos carroID y mejoraCarroID
     tiene como elementos hijos el Automovil y tipo Carro el cual tiene el diseño-->
    <xs:element name="Carro">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Automovil"/>
                <xs:element ref="TipoCarro"/>
            </xs:sequence>
            <xs:attribute name="carroID" type="xs:string" use="required"/>
            <xs:attribute name="mejoraCarroID" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="TipoCarro">
        <xs:complexType>
            <xs:attribute name="Diseno" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <!-- Elemento Camionetas que es uno hijo del de Lista Vehiculos
     Tiene como elemento Hijo la Camioneta-->
    <xs:element name="Camionetas">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Camioneta" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- elemento camioneta que tiene como atributo camionetaID
    y como elementos Automovil y tipoCamioneta -->
    <xs:element name="Camioneta">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Automovil"/>
                <xs:element ref="TipoCamioneta"/>
            </xs:sequence>
            <xs:attribute name="camionetaID" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <!-- elemento tipo camioneta que es un hijo de camioneta y por atritubo el diseño -->
    <xs:element name="TipoCamioneta">
        <xs:complexType>
            <xs:attribute name="Diseno" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

	<!-- elemento automovil que es uno hijo de Moto, Carro, Camioneta
	 tiene como atributos, condicion, transmision, imagen, y el tipo imagen
	 tiene como elementos hijos marca, modelo, color, precio, kilometraje, description -->
    <xs:element name="Automovil">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Marca"/>
                <xs:element ref="Modelo"/>
                <xs:element ref="Color"/>
                <xs:element ref="Precio"/>
                <xs:element ref="Kilometraje"/>
                <xs:element ref="Descripcion"/>
            </xs:sequence>
            <xs:attribute name="Condicion" type="xs:string" use="required"/>
            <xs:attribute name="Transmision" type="xs:string" use="required"/>
            <xs:attribute name="Imagen" type="xs:string" use="required"/>
            <xs:attribute name="TipoImagen" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
	<!-- los elementos hijos de automovil -->
	<xs:element name="Marca" type="xs:string"/>
	<xs:element name="Modelo">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="Anio"/>
				<xs:element ref="Version" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Anio" type="xs:string"/>
	<xs:element name="Version" type="xs:string"/>
    <xs:element name="Color" type="xs:string"/>
	<xs:element name="Precio" type="xs:string"/>
    <xs:element name="Kilometraje" type="xs:string"/>
	<xs:element name="Descripcion" type="xs:string"/>
    <!-- el elemento Pie de pagia que es uno hijo del elemento Concesionaria -->
    <xs:element name="PiePagina" type="xs:string"/>
</xs:schema>

=== enriquecr1990/masterunirmex/materias/1er_semestre/letw/dtd_a_schema_xml/vehiculos_xsl.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="xsl/vehiculos.xsl" ?>
<Concesionaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			   xsi:noNamespaceSchemaLocation="xsd/vehiculos_schema.xsd" Compania="EnriqueAsociados">
	<ListaVehiculos TiposVehiculos="Motos Carros Camionetas">
		<Motos>
			<Moto motoID="Moto1">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/yamaha-mt15.jpg" TipoImagen="jpg">
					<Marca>Yamaha</Marca>
					<Modelo>
						MT-15
						<Anio>2020</Anio>
					</Modelo>
					<Color>Rojo con Negro</Color>
					<Precio>85999.99</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Con un motor de alta tecnología, una carrocería compacta y un diseño propio de la linea MT de próxima generación, esta nueva y emocionante motocicleta no tiene comparación. Prepárate para activar tu lado oscuro. Porque esta ligera Hyper Naked va a transformar tu mundo. La nueva MT-15, gracias a su aspecto agresivo, demuestra toda su actitud incluso cuando no se mueve. Las nuevas y llamativas luces de posición dobles aportan a esta Hyper Naked ultraligera el aspecto más intimidante de su categoría. La robusta carrocería echada hacia adelante parece lista para atacar en cualquier momento. </Descripcion>
				</Automovil>
			</Moto>
		</Motos>
		<Carros>
			<Carro carroID="cSpark2021">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/chevrolet-spark-2020.png" TipoImagen="png">
					<Marca>Chevrolet</Marca>
					<Modelo>
						Spark
						<Anio>2021</Anio>
						<Version>LS 3 Cilindros</Version>
					</Modelo>
					<Color>Azul Metálico</Color>
					<Precio>183700.00</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Chevrolet Spark es el auto para ti, pues gracias a su tecnología y equipamiento te da info-entretenimiento, conectividad y seguridad únicos.</Descripcion>
				</Automovil>
				<TipoCarro Diseno="Hatchback" />
			</Carro>
			<Carro carroID="fFusion2019">
				<Automovil Condicion="Seminuevo" Transmision="Automatico" Imagen="imagenes/ford-fusion-2019-sedan.jpg" TipoImagen="jpg">
					<Marca>Ford</Marca>
					<Modelo>
						Fusion
						<Anio>2019</Anio>
					</Modelo>
					<Color>Azul Marino Metalizado</Color>
					<Precio>175999.00</Precio>
					<Kilometraje>30000</Kilometraje>
					<Descripcion>Déjate cautivar por Ford Fusion 2020, auto sedán de espectacular, el conjunto de tecnologías pensadas para brindarte una experiencia de conducción llena de confort, dinamismo y seguridad al máximo. ¡Descúbrelo! </Descripcion>
				</Automovil>
				<TipoCarro Diseno="Sedan" />
			</Carro>
			<Carro  carroID="fFusion2020" mejoraCarroID="fFusion2019">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/ford-fusion-2020-sedan.jpg" TipoImagen="jpg">
					<Marca>Ford</Marca>
					<Modelo>
						Fusion
						<Anio>2020</Anio>
					</Modelo>
					<Color>Blanco</Color>
					<Precio>265800.00</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Déjate cautivar por Ford Fusion 2020, auto sedán de espectacular Diseño equipado con Co-Pilot360, el conjunto de tecnologías pensadas para brindarte una experiencia de conducción llena de confort, dinamismo y seguridad al máximo. ¡Descúbrelo! </Descripcion>
				</Automovil>
				<TipoCarro Diseno="Sedan" />
			</Carro>
		</Carros>
		<Camionetas>
			<Camioneta camionetaID="camioneta0001">
				<Automovil Condicion="Nuevo" Transmision="Manual" Imagen="imagenes/ford-ranger-2020.jpg" TipoImagen="jpg" >
					<Marca>Ford</Marca>
					<Modelo>
						Ranger
						<Anio>2020</Anio>
					</Modelo>
					<Color>Azul Metalizado</Color>
					<Precio>424600.00</Precio>
					<Kilometraje>0</Kilometraje>
					<Descripcion>Ya sea que conduzcas por placer o trabajo, Ford Ranger 2020 tiene el Poder y Resistencia necesarios para acompañarte en cualquier actividad. ¡Ford Ranger 2020 tiene todo lo que deseas de una Camioneta Pick Up!</Descripcion>
				</Automovil>
				<TipoCamioneta Diseno="DobleCabina" />
			</Camioneta>
		</Camionetas>
	</ListaVehiculos>
	<PiePagina>
		Estudiante: Enrique Corona Ricaño - Materia: Lenguajes, Estándares y Tecnologías para la Web
	</PiePagina>
</Concesionaria>
